# -*- coding: utf-8 -*-
"""Code_generation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o01jq5T1faG9J_FFpqOtQ5vMXUcKANNk
"""

!pip install transformers datasets
!pip install transformers[torch] accelerate -U

!pip install PyGithub datasets

import torch

from github import Github
import re
from datasets import Dataset

g = Github("GITHUB_API_KEY")

"""##Getting the specific repository from the github"""

repo = g.get_repo("openai/gym")

"""It scans the given code as text, finds every line that looks like a Python function definition (def function_name(...) :), and returns a list of the function names."""

def extraction_fun_name(code):
    pattern = re.compile(r"def\s+(\w+)\s*\(.*\):")
    functions = pattern.findall(code)
    return functions

"""It walks through every directory in the repository, finds files ending with .py, and stores them in a list."""

python_files =[]
contents = repo.get_contents("")
while contents:
  file_content= contents.pop(0)
  if file_content.type == "dir":
    contents.extend(repo.get_contents(file_content.path))
  elif file_content.path.endswith(".py"):
    python_files.append(file_content)

"""For every Python file in the repository, it extracts all function names and pairs each function name with the full source code of the file.


"""

data = {"code":[], "function_name":[]}

for file in python_files:
  code=file.decoded_content.decode("utf-8")
  functions=extraction_fun_name(code)
  for function in functions:
    data["code"].append(code)
    data["function_name"].append(function)

dataset=Dataset.from_dict(data)

dataset.save_to_disk("code_generation_dataset")

print("Dataset created and saved to disk.")

"""It sets up a tokenizer and model, loads a saved dataset, splits it into training and testing sets, enables memory-efficient training, and defines how raw code will be converted into model-ready tokens."""

from datasets import load_from_disk
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments

tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-350M-mono")
model =AutoModelForCausalLM.from_pretrained("Salesforce/codegen-350M-mono")
tokenizer.pad_token=tokenizer.eos_token
dataset=dataset.load_from_disk("code_generation_dataset")
dataset=dataset.train_test_split(test_size=0.1)
model.gradient_checkpointing_enable()
model.config.use_cache = False

def preprocess_function(examples):
  return tokenizer(
      examples["code"],
      truncation=True,
      max_length=256,
      padding="max_length"
    )

"""It converts raw code into token IDs, frees unused GPU memory, and defines how the model will be trained while minimizing GPU memory usage."""

tokenized_dataset= dataset.map(preprocess_function,batched=True)
torch.cuda.empty_cache()
training_args =TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    num_train_epochs=1,
    save_steps=10_000,
    save_total_limit=2,
    # --- Memory Saving Settings ---
    fp16=True,
    gradient_checkpointing=True,
    optim="adamw_torch_fused",
    dataloader_pin_memory=True
)

"""It prepares batches of tokenized code so the model can learn to predict the next token in a sequence, which is how code-generation models are trained."""

from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

"""It connects the model, training configuration, prepared datasets, and data collator, then begins training the model on the code data."""

trainer=Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset['train'],
    eval_dataset=tokenized_dataset['test'],
    data_collator=data_collator,
)
trainer.train()

"""You give the model the beginning of a function, and it automatically completes the code based on what it learned during training."""

def generate_code(prompt, max_length=300):
    model.eval()
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            inputs["input_ids"],
            max_length=max_length
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)


# test the model with a code generation prompt
prompt = "def binary_search(arr):"
generated_code = generate_code(prompt)

print("Generated Code:")
print(generated_code)

